[I 200831 16:37:39 settings:125] WarningPolicy
[I 200831 16:38:40 settings:125] WarningPolicy
[I 200831 16:38:53 settings:125] WarningPolicy
[I 200831 16:38:53 main:39] Listening on 127.0.0.1:654321 (http)
[I 200831 16:38:53 main:39] Listening on :4433 (https)
[I 200831 16:39:46 settings:125] WarningPolicy
[I 200831 16:39:46 main:39] Listening on 127.0.0.1:654321 (http)
[I 200831 16:39:46 main:39] Listening on :4433 (https)
[I 200831 16:40:22 settings:125] WarningPolicy
[I 200831 16:40:22 main:39] Listening on 127.0.0.1:654321 (http)
[I 200831 16:40:22 main:39] Listening on :4433 (https)
[I 200831 16:40:42 settings:125] WarningPolicy
[I 200831 16:40:42 main:39] Listening on 127.0.0.1:65432 (http)
[I 200831 16:40:42 main:39] Listening on :4433 (https)
[I 200831 16:40:45 web:2250] 200 GET / (127.0.0.1) 8.85ms
[I 200831 16:40:46 web:2250] 200 GET /static/css/bootstrap.min.css (127.0.0.1) 12.20ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/xterm.min.js (127.0.0.1) 11.96ms
[I 200831 16:40:46 web:2250] 200 GET /static/css/xterm.min.css (127.0.0.1) 12.50ms
[I 200831 16:40:46 web:2250] 200 GET /static/css/fullscreen.min.css (127.0.0.1) 12.52ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/jquery.min.js (127.0.0.1) 13.41ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/popper.min.js (127.0.0.1) 13.91ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/bootstrap.min.js (127.0.0.1) 20.84ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/xterm-addon-fit.min.js (127.0.0.1) 4.83ms
[I 200831 16:40:46 web:2250] 200 GET /static/js/main.js (127.0.0.1) 6.36ms
[I 200831 16:40:46 web:2250] 200 GET /static/img/favicon.png (127.0.0.1) 2.10ms
[I 200831 16:41:01 web:2250] 200 GET / (127.0.0.1) 1.24ms
[I 200831 16:41:01 web:2250] 200 GET /static/css/bootstrap.min.css (127.0.0.1) 1.51ms
[I 200831 16:41:01 web:2250] 200 GET /static/css/xterm.min.css (127.0.0.1) 1.51ms
[I 200831 16:41:01 web:2250] 200 GET /static/css/fullscreen.min.css (127.0.0.1) 6.30ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/jquery.min.js (127.0.0.1) 6.20ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/popper.min.js (127.0.0.1) 8.09ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/bootstrap.min.js (127.0.0.1) 6.88ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/xterm.min.js (127.0.0.1) 3.75ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/xterm-addon-fit.min.js (127.0.0.1) 5.98ms
[I 200831 16:41:01 web:2250] 200 GET /static/js/main.js (127.0.0.1) 1.46ms
[I 200831 16:41:01 web:2250] 200 GET /static/img/favicon.png (127.0.0.1) 1.35ms
[I 200831 16:41:07 http1connection:289] Malformed HTTP message from 127.0.0.1: no colon in header line
[I 200831 16:41:37 http1connection:289] Malformed HTTP message from 127.0.0.1: no colon in header line
[I 200831 16:42:07 settings:125] WarningPolicy
[I 200831 16:42:07 main:39] Listening on 127.0.0.1:65432 (http)
[I 200831 16:42:07 main:39] Listening on :4433 (https)
[I 200831 16:42:27 web:2250] 200 GET / (127.0.0.1) 7.38ms
[W 200831 16:42:34 web:2250] 404 GET /static/js/popper.min.js.map (127.0.0.1) 2.57ms
[W 200831 16:42:34 web:2250] 404 GET /static/js/bootstrap.min.js.map (127.0.0.1) 3.28ms
[W 200831 16:42:34 web:2250] 404 GET /static/js/xterm.js.map (127.0.0.1) 2.54ms
[W 200831 16:42:34 web:2250] 404 GET /static/js/xterm-addon-fit.js.map (127.0.0.1) 2.22ms
[W 200831 16:42:34 web:2250] 404 GET /static/css/bootstrap.min.css.map (127.0.0.1) 4.00ms
[W 200831 16:42:34 web:2250] 404 GET /static/css/fullscreen.min.css.map (127.0.0.1) 11.53ms
[I 200831 16:42:56 handler:447] Connecting to 192.168.0.109:22
[E 200831 16:42:59 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in connect
        retry_on_signal(lambda: sock.connect(addr))
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/util.py", line 279, in retry_on_signal
        return function()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in <lambda>
        retry_on_signal(lambda: sock.connect(addr))
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 452, in ssh_connect
        raise ValueError('Unable to connect to {}:{}'.format(*dst_addr))
    ValueError: Unable to connect to 192.168.0.109:22
    
[I 200831 16:42:59 web:2250] 200 POST / (127.0.0.1) 3014.19ms
[I 200831 16:43:08 handler:447] Connecting to 192.168.0.110:22
[E 200831 16:43:11 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in connect
        retry_on_signal(lambda: sock.connect(addr))
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/util.py", line 279, in retry_on_signal
        return function()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in <lambda>
        retry_on_signal(lambda: sock.connect(addr))
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 452, in ssh_connect
        raise ValueError('Unable to connect to {}:{}'.format(*dst_addr))
    ValueError: Unable to connect to 192.168.0.110:22
    
[I 200831 16:43:11 web:2250] 200 POST / (127.0.0.1) 3004.46ms
[I 200831 16:43:51 handler:447] Connecting to 192.168.0.110:22
[E 200831 16:43:54 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in connect
        retry_on_signal(lambda: sock.connect(addr))
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/util.py", line 279, in retry_on_signal
        return function()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 338, in <lambda>
        retry_on_signal(lambda: sock.connect(addr))
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 452, in ssh_connect
        raise ValueError('Unable to connect to {}:{}'.format(*dst_addr))
    ValueError: Unable to connect to 192.168.0.110:22
    
[I 200831 16:43:54 web:2250] 200 POST / (127.0.0.1) 3006.91ms
[I 200831 16:46:59 handler:447] Connecting to 192.168.0.106:22
[I 200831 16:46:59 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 16:46:59 handler:87] Trying password authentication
[I 200831 16:47:02 transport:1687] Authentication (password) failed.
[E 200831 16:47:02 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 424, in connect
        passphrase,
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 101, in _auth
        raise saved_exception
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 89, in _auth
        self._transport.auth_password(username, password)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1381, in auth_password
        return self.auth_handler.wait_for_response(my_event)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/auth_handler.py", line 226, in wait_for_response
        raise e
    paramiko.ssh_exception.AuthenticationException: Authentication failed.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 456, in ssh_connect
        raise ValueError('Authentication failed.')
    ValueError: Authentication failed.
    
[I 200831 16:47:02 web:2250] 200 POST / (127.0.0.1) 3707.76ms
[I 200831 16:47:07 handler:447] Connecting to 192.168.0.106:22
[I 200831 16:47:07 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 16:47:07 handler:87] Trying password authentication
[I 200831 16:47:07 transport:1687] Authentication (password) successful!
[W 200831 16:47:08 handler:441] Could not detect the default ecnoding.
[I 200831 16:47:08 web:2250] 200 POST / (127.0.0.1) 501.67ms
[I 200831 16:47:08 web:2250] 101 GET /ws?id=140213148310048 (127.0.0.1) 0.87ms
[I 200831 16:47:08 handler:533] Connected from 127.0.0.1:44174
[I 200831 16:53:49 settings:125] WarningPolicy
[I 200831 16:53:49 main:39] Listening on 127.0.0.1:65432 (http)
[I 200831 16:53:49 main:39] Listening on :4433 (https)
[I 200831 16:53:59 settings:125] WarningPolicy
[I 200831 16:53:59 main:39] Listening on 127.0.0.1:65432 (http)
[I 200831 16:53:59 main:39] Listening on :4433 (https)
[I 200831 16:54:14 web:2250] 200 GET / (127.0.0.1) 9.39ms
[I 200831 18:13:12 http1connection:289] Malformed HTTP message from 127.0.0.1: no colon in header line
[I 200831 18:14:02 web:2250] 200 GET /?title=Rasp%20MV&hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 3.71ms
[I 200831 18:14:02 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:14:02 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[E 200831 18:14:05 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 398, in connect
        server_key = t.get_remote_server_key()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 720, in get_remote_server_key
        raise SSHException('No existing session')
    paramiko.ssh_exception.SSHException: No existing session
    
[I 200831 18:14:05 web:2250] 200 POST /?title=Rasp%20MV&hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 3070.15ms
[I 200831 18:14:16 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:14:17 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[E 200831 18:14:20 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 398, in connect
        server_key = t.get_remote_server_key()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 720, in get_remote_server_key
        raise SSHException('No existing session')
    paramiko.ssh_exception.SSHException: No existing session
    
[I 200831 18:14:20 web:2250] 200 POST /?title=Rasp%20MV&hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 3025.60ms
[W 200831 18:14:56 web:2250] 404 GET /static/js/popper.min.js.map (127.0.0.1) 7.44ms
[W 200831 18:14:56 web:2250] 404 GET /static/js/bootstrap.min.js.map (127.0.0.1) 8.14ms
[W 200831 18:14:56 web:2250] 404 GET /static/js/xterm.js.map (127.0.0.1) 4.98ms
[W 200831 18:14:56 web:2250] 404 GET /static/js/xterm-addon-fit.js.map (127.0.0.1) 2.44ms
[W 200831 18:14:57 web:2250] 404 GET /static/css/bootstrap.min.css.map (127.0.0.1) 1.37ms
[W 200831 18:14:57 web:2250] 404 GET /static/css/fullscreen.min.css.map (127.0.0.1) 1.12ms
[I 200831 18:15:15 web:2250] 200 GET /?title=Rasp%20MV&hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 1.99ms
[I 200831 18:15:15 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:15:15 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[E 200831 18:15:18 handler:511] Traceback (most recent call last):
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 509, in post
        worker = yield future
      File "/home/equipo/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/equipo/.local/lib/python3.5/site-packages/webssh/handler.py", line 450, in ssh_connect
        ssh.connect(*args, timeout=options.timeout)
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/client.py", line 398, in connect
        server_key = t.get_remote_server_key()
      File "/home/equipo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 720, in get_remote_server_key
        raise SSHException('No existing session')
    paramiko.ssh_exception.SSHException: No existing session
    
[I 200831 18:15:18 web:2250] 200 POST /?title=Rasp%20MV&hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 3050.91ms
[I 200831 18:15:23 web:2250] 200 GET /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 1.24ms
[I 200831 18:15:23 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:15:23 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:16:13 web:2250] 200 GET /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 1.56ms
[I 200831 18:16:14 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:16:14 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:16:14 handler:87] Trying password authentication
[I 200831 18:16:14 transport:1687] Authentication (password) successful!
[W 200831 18:16:14 handler:441] Could not detect the default ecnoding.
[I 200831 18:16:14 web:2250] 200 POST /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 576.24ms
[I 200831 18:16:14 web:2250] 101 GET /ws?id=139641891842872 (127.0.0.1) 1.38ms
[I 200831 18:16:14 handler:533] Connected from 127.0.0.1:58920
[I 200831 18:16:16 handler:579] Disconnected from 127.0.0.1:58920
[I 200831 18:16:16 worker:115] Closing worker 139641891842872 with reason: client disconnected
[I 200831 18:16:16 worker:122] Connection to 192.168.0.106:22 lost
[I 200831 18:16:28 web:2250] 200 GET /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 1.59ms
[I 200831 18:16:28 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:16:28 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:16:28 handler:87] Trying password authentication
[I 200831 18:16:28 transport:1687] Authentication (password) successful!
[W 200831 18:16:28 handler:441] Could not detect the default ecnoding.
[I 200831 18:16:28 web:2250] 200 POST /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (127.0.0.1) 562.15ms
[I 200831 18:16:28 web:2250] 101 GET /ws?id=139641891842760 (127.0.0.1) 0.75ms
[I 200831 18:16:28 handler:533] Connected from 127.0.0.1:59042
[I 200831 18:17:39 handler:579] Disconnected from 127.0.0.1:59042
[I 200831 18:17:39 worker:115] Closing worker 139641891842760 with reason: client disconnected
[I 200831 18:17:39 worker:122] Connection to 192.168.0.106:22 lost
[I 200831 18:17:47 web:2250] 200 GET /?hostname=192.168.0.110&username=pi&password=YWRtaW4jMTAwOQ== (127.0.0.1) 2.12ms
[I 200831 18:17:47 handler:447] Connecting to 192.168.0.110:22
[I 200831 18:17:48 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:18:07 web:2250] 200 GET /?hostname=192.168.0.110&username=pi&password=YWRtaW4jMTAwOQ== (127.0.0.1) 2.34ms
[I 200831 18:18:07 handler:447] Connecting to 192.168.0.110:22
[I 200831 18:18:07 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:18:07 handler:87] Trying password authentication
[I 200831 18:18:08 transport:1687] Authentication (password) successful!
[I 200831 18:18:09 web:2250] 200 POST /?hostname=192.168.0.110&username=pi&password=YWRtaW4jMTAwOQ== (127.0.0.1) 2037.31ms
[I 200831 18:18:09 web:2250] 101 GET /ws?id=139641926164264 (127.0.0.1) 0.86ms
[I 200831 18:18:09 handler:533] Connected from 127.0.0.1:59862
[I 200831 18:21:53 handler:87] Trying password authentication
[I 200831 18:21:53 handler:87] Trying password authentication
[I 200831 18:22:39 settings:125] RejectPolicy
[I 200831 18:22:39 main:39] Listening on 127.0.0.1:54321 (http)
[I 200831 18:22:39 main:39] Listening on :65432 (https)
[W 200831 18:22:52 iostream:1433] SSL Error on 12 ('::1', 45364, 0, 0): [SSL: HTTP_REQUEST] http request (_ssl.c:645)
[W 200831 18:22:52 iostream:1433] SSL Error on 12 ('::1', 45366, 0, 0): [SSL: HTTP_REQUEST] http request (_ssl.c:645)
[W 200831 18:22:56 iostream:1433] SSL Error on 12 ('::1', 45400, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 12 ('::1', 45436, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:23:00 web:2250] 200 GET / (::1) 5.12ms
[I 200831 18:23:00 web:2250] 200 GET /static/css/bootstrap.min.css (::1) 26.20ms
[W 200831 18:23:00 iostream:1433] SSL Error on 13 ('::1', 45440, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 14 ('::1', 45442, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 15 ('::1', 45444, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 16 ('::1', 45446, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 17 ('::1', 45448, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:23:00 web:2250] 200 GET /static/css/xterm.min.css (::1) 25.37ms
[W 200831 18:23:00 iostream:1433] SSL Error on 13 ('::1', 45450, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 14 ('::1', 45452, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 15 ('::1', 45454, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 16 ('::1', 45456, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[W 200831 18:23:00 iostream:1433] SSL Error on 17 ('::1', 45458, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:23:00 web:2250] 200 GET /static/css/fullscreen.min.css (::1) 8.13ms
[W 200831 18:23:00 iostream:1433] SSL Error on 13 ('::1', 45460, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:23:00 web:2250] 200 GET /static/js/popper.min.js (::1) 4.99ms
[I 200831 18:23:00 web:2250] 200 GET /static/js/xterm.min.js (::1) 10.61ms
[I 200831 18:23:00 web:2250] 200 GET /static/js/xterm-addon-fit.min.js (::1) 2.59ms
[I 200831 18:23:00 web:2250] 200 GET /static/js/main.js (::1) 6.38ms
[I 200831 18:23:00 web:2250] 200 GET /static/js/jquery.min.js (::1) 5.89ms
[I 200831 18:23:00 web:2250] 200 GET /static/js/bootstrap.min.js (::1) 6.81ms
[W 200831 18:23:01 web:2250] 404 GET /static/css/bootstrap.min.css.map (::1) 4.48ms
[W 200831 18:23:01 web:2250] 404 GET /static/css/fullscreen.min.css.map (::1) 1.69ms
[W 200831 18:23:01 web:2250] 404 GET /static/js/popper.min.js.map (::1) 2.96ms
[W 200831 18:23:01 web:2250] 404 GET /static/js/bootstrap.min.js.map (::1) 0.74ms
[W 200831 18:23:01 web:2250] 404 GET /static/js/xterm.js.map (::1) 1.08ms
[W 200831 18:23:01 web:2250] 404 GET /static/js/xterm-addon-fit.js.map (::1) 1.01ms
[I 200831 18:23:01 web:2250] 200 GET /static/img/favicon.png (::1) 5.99ms
[I 200831 18:23:58 web:2250] 200 GET /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (::1) 4.25ms
[I 200831 18:23:59 web:2250] 200 GET /static/css/bootstrap.min.css (::1) 2.97ms
[I 200831 18:23:59 web:2250] 200 GET /static/css/xterm.min.css (::1) 9.41ms
[I 200831 18:23:59 web:2250] 200 GET /static/css/fullscreen.min.css (::1) 12.51ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/jquery.min.js (::1) 13.63ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/popper.min.js (::1) 20.49ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/bootstrap.min.js (::1) 4.41ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/xterm.min.js (::1) 14.64ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/xterm-addon-fit.min.js (::1) 15.64ms
[I 200831 18:23:59 web:2250] 200 GET /static/js/main.js (::1) 3.35ms
[I 200831 18:23:59 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:23:59 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:23:59 handler:87] Trying password authentication
[I 200831 18:23:59 transport:1687] Authentication (password) successful!
[W 200831 18:24:00 handler:441] Could not detect the default ecnoding.
[I 200831 18:24:00 web:2250] 200 POST /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (::1) 578.90ms
[W 200831 18:24:00 iostream:1433] SSL Error on 21 ('::1', 45502, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:24:00 web:2250] 101 GET /ws?id=140238424003472 (::1) 1.32ms
[I 200831 18:24:00 handler:533] Connected from ::1:45504
[I 200831 18:24:14 handler:579] Disconnected from ::1:45504
[I 200831 18:24:14 worker:115] Closing worker 140238424003472 with reason: client disconnected
[I 200831 18:24:14 worker:122] Connection to 192.168.0.106:22 lost
[I 200831 18:24:15 web:2250] 200 GET /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (::1) 1.53ms
[I 200831 18:24:15 web:2250] 200 GET /static/css/bootstrap.min.css (::1) 2.03ms
[I 200831 18:24:15 web:2250] 200 GET /static/css/xterm.min.css (::1) 4.99ms
[I 200831 18:24:15 web:2250] 200 GET /static/css/fullscreen.min.css (::1) 8.50ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/jquery.min.js (::1) 14.30ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/popper.min.js (::1) 20.86ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/bootstrap.min.js (::1) 31.38ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/xterm.min.js (::1) 29.77ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/xterm-addon-fit.min.js (::1) 8.77ms
[I 200831 18:24:15 web:2250] 200 GET /static/js/main.js (::1) 5.67ms
[I 200831 18:24:15 handler:447] Connecting to 192.168.0.106:22
[I 200831 18:24:15 transport:1687] Connected (version 2.0, client OpenSSH_7.9p1)
[I 200831 18:24:15 handler:87] Trying password authentication
[I 200831 18:24:15 transport:1687] Authentication (password) successful!
[W 200831 18:24:16 handler:441] Could not detect the default ecnoding.
[I 200831 18:24:16 web:2250] 200 POST /?hostname=192.168.0.106&username=pi&password=YWRtaW4xMDA5 (::1) 538.53ms
[W 200831 18:24:16 iostream:1433] SSL Error on 21 ('::1', 45528, 0, 0): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)
[I 200831 18:24:16 web:2250] 101 GET /ws?id=140238423990112 (::1) 0.67ms
[I 200831 18:24:16 handler:533] Connected from ::1:45530
[I 200831 18:56:54 settings:125] RejectPolicy
[I 200831 18:56:54 main:39] Listening on 127.0.0.1:54321 (http)
[I 200831 18:56:54 main:39] Listening on :65432 (https)
